# Generated by Django 2.1.3 on 2020-09-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('landlord_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('image1', models.ImageField(default='pics', upload_to='pics')),
                ('image2', models.ImageField(default='pics', upload_to='pics')),
                ('image3', models.ImageField(default='pics', upload_to='pics')),
                ('image4', models.ImageField(default='pics/%s-%s', upload_to='pics/%s-%s')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('landlord', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('landlord_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics', verbose_name='Image')),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shelttry.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('landlord', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('image1', models.FileField(null=True, upload_to='pics/')),
                ('image2', models.FileField(null=True, upload_to='pics/')),
                ('image3', models.FileField(null=True, upload_to='pics/')),
                ('image4', models.FileField(null=True, upload_to='pics/')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelttry.Post'),
        ),
    ]
