# Generated by Django 2.1.3 on 2020-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='extra_facility',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
