# Generated by Django 2.1.3 on 2020-06-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0002_auto_20200625_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='landlord_name',
            new_name='landlord',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
