# Generated by Django 2.1.3 on 2020-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0002_auto_20200912_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
