# Generated by Django 2.1.3 on 2020-10-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0004_upload_avaliability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='avaliability',
            new_name='availability',
        ),
    ]
