# Generated by Django 2.1.3 on 2020-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
