# Generated by Django 2.1.3 on 2020-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0007_auto_20201014_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
