# Generated by Django 3.1.5 on 2021-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0008_auto_20201019_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image10',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image5',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image6',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image7',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image8',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image9',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='numbers',
            field=models.IntegerField(null=True),
        ),
    ]
